### ISSUE TITLE
TGEs missing

### ISSUE THREAD

**Issue by saha-shyamasree** [bezzlab/pitdb#16]
Apparently TGE2 is a known human Protein, but http://pitdb.eu-west-1.elasticbeanstalk.com/protein?uniprot=P07437 page did not show anything.

**Comment by saha-shyamasree** [comment]
How do we calculate Average peptides per TGE? For following TGE, it seems there are 190 peptides all together (not unique) for 15 TGEs. The average peptide per coverage is 6.52 according to the result, It some how sounds wrong to me.
http://pitdb.eu-west-1.elasticbeanstalk.com/tge?accession=TGE000002

**Comment by saha-shyamasree** [comment]
Is average peptides per TGEs fixed? I have checked 3 TGEs, all showing 6.52. Here are they
http://pitdb.eu-west-1.elasticbeanstalk.com/tge?accession=TGE044436
http://pitdb.eu-west-1.elasticbeanstalk.com/tge?accession=TGE000002
http://pitdb.eu-west-1.elasticbeanstalk.com/tge?accession=TGE001234

**Comment by eaHat** [comment]
Problem (1) fixed (tbd when you are back
Problems (2) and (3) .. I had forgotten a 'filter_by' tge.id statement so should have the right number now. Thanks for spotting!
