### ISSUE TITLE
Remove experiment names; Use proper experiment accession numbers

### ISSUE THREAD

**Issue by conradbessant** [bezzlab/pitdb#18]
The free text experiment names, e.g. "Bat", "Mouse", are a bit confusing. Suggest removing this and using only experiment accession numbers to identify experiments, e.g. PIT00001 etc.

**Comment by eaHat** [comment]
No problem. We don't have any consistent format though for experiment IDs (like PIT00001). We just have numbers 1,2 ,3 etc. Do we want to create PIT+0s+num?

**Comment by conradbessant** [comment]
Yes. Like you did with TGEs.

**Comment by eaHat** [comment]
OK.. will need to change the DB and search as well. Should not be too hard to do though
