### ISSUE TITLE
Conversion of alternate sequence

### ISSUE THREAD

**Issue by eaHat** [bezzlab/pitdb#30]
chr6_GL000255v2_alt 

GL000255.2

for @saha-shyamasree to investigate and make sure it works properly

**Comment by saha-shyamasree** [comment]
It seems we dont need to convert it after all. I have added those alternative chromosomes in the js file and it works. I have added it grch38.js in Genoverse folder under PIT-DB in fropbox.
![alternativeseq](https://cloud.githubusercontent.com/assets/2076522/17304347/22db6f3a-581d-11e6-9c8c-7900c76235b1.png)
