### ISSUE TITLE
Add TGE table to Experiment

### ISSUE THREAD

**Issue by conradbessant** [bezzlab/pitdb#56]
Currently no easy way to see TGEs from a specific experiment

**Comment by eaHat** [comment]
@conradbessant fixed.. is this what we are looking for? 
<img width="983" alt="screen shot 2016-08-14 at 10 16 21" src="https://cloud.githubusercontent.com/assets/6576711/17647751/35a76944-6208-11e6-9720-f55ae1707259.png">

<img width="749" alt="screen shot 2016-08-14 at 10 17 24" src="https://cloud.githubusercontent.com/assets/6576711/17647756/548f9c8c-6208-11e6-83ee-4700de87b611.png">

**Comment by eaHat** [comment]
Also added organisms .. updated version here: http://localhost:8080/experiment?experiment=PIT000001

**Comment by conradbessant** [comment]
Looking good.
